var pip = "ciao"

var icon_dict = new Map();
icon_dict.set("before am", "️️🅰️");
icon_dict.set("before arg", "🇦🇷");
icon_dict.set("before box", "🥊");
icon_dict.set("before br", "🇧🇷");
icon_dict.set("before cc2017", "🏆");
icon_dict.set("before oro", "🏆");
icon_dict.set("before caf", "🏆");
icon_dict.set("before ch", "🏆");
icon_dict.set("before ci", "🚲");
icon_dict.set("before cl", "🇨🇱");
icon_dict.set("before co", "🇨🇴");
icon_dict.set("before de", "🇩🇪");
icon_dict.set("before ec", "🇪🇨");
icon_dict.set("before en", "🇬🇧");
icon_dict.set("before es", "🇪🇸");
icon_dict.set("before f1", "🏁");
icon_dict.set("before fr", "🇫🇷");
icon_dict.set("before it", "🇮🇹");
icon_dict.set("before mlb", "⚾️");
icon_dict.set("before mx", "🇲🇽");
icon_dict.set("before ca2019", "🏆");
icon_dict.set("before nba", "🏀");
icon_dict.set("before nl", "🇳🇱");
icon_dict.set("before pe", "🇵🇪");
icon_dict.set("before csuda", "🏆");
icon_dict.set("before tr", "🇹🇷");
icon_dict.set("before us", "🇺🇸");
icon_dict.set("before el", "🏆");
icon_dict.set("before uy", "🇺🇾");
icon_dict.set("before wwe", "🤼‍");
icon_dict.set("before suda", "🏆");
icon_dict.set("before bkb", "🏀");
icon_dict.set("before tenis", "🎾");
icon_dict.set("before motogp", "🏍️");
icon_dict.set("before soccer", "⚽");
icon_dict.set("before icc", "🏆");

var url_dict = new Map();
url_dict.set("bein", "1");
url_dict.set("beinn", "1");
url_dict.set("canal-31", "1");
url_dict.set("canal1", "1");
url_dict.set("canal2", "1");
url_dict.set("directv", "1");
url_dict.set("dplus", "1");
url_dict.set("espn3", "1");
url_dict.set("fox2", "1");
url_dict.set("futbol", "1");
url_dict.set("gol", "1");
url_dict.set("santander", "1");
url_dict.set("skip", "1");
url_dict.set("canal-42", "1");
url_dict.set("canal-30", "1");
url_dict.set("canal-41", "1");

exports.icon_dict = icon_dict;
exports.url_dict = url_dict;
